[package]
name = "db-check"
version = "0.1.0"
edition = "2021"

[dependencies]
reth-db.workspace = true
reth-db-api.workspace = true
reth-chainspec.workspace = true
reth-provider.workspace = true
reth-node-types.workspace = true
reth-stages.workspace = true
reth-tasks.workspace = true
reth-node-ethereum.workspace = true
anyhow.workspace = true
clap = { version = "4.5.30", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
